export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const START_PRODUCTS = 'START_PRODUCTS';
export const END_PRODUCTS = 'END_PRODUCTS';

export const GET_DATA_USERS = 'GET_DATA_USERS';
export const START_GET_USERS = 'START_GET_USERS';
export const END_GET_USERS = 'END_GET_USERS';

export const START_GET_TRANSACTIONS = 'START_GET_TRANSACTIONS';
export const GET_DATA_TRANSACTIONS = 'GET_DATA_TRANSACTIONS';
export const END_GET_TRANSACTIONS = 'END_GET_TRANSACTIONS';

export const START_DETAIL_TRANSACTION = 'START_DETAIL_TRANSACTION';
export const GET_DETAIL_TRANSACTION = 'GET_DETAIL_TRANSACTION';
export const END_DETAIL_TRANSACTION = 'END_DETAIL_TRANSACTION';

export const UPDATE_STATUS_TRANSACTION = 'UPDATE_STATUS_TRANSACTION';
export const START_UPDATE_STATUS_TRANSACTION = 'START_UPDATE_STATUS_TRANSACTION';
export const END_UPDATE_STATUS_TRANSACTION = 'END_UPDATE_STATUS_TRANSACTION';
export const GET_COMBO_STATUS_TRANSACTION = 'GET_COMBO_STATUS_TRANSACTION';

export const START_GET_TOTAL_DATA = 'START_GET_TOTAL_DATA';
export const GET_TOTAL_DATA = 'GET_TOTAL_DATA';
export const END_GET_TOTAL_DATA = 'END_GET_TOTAL_DATA';
export const GET_SALES_PRODUCT = 'GET_SALES_PRODUCT';
export const GET_INCOME_STATEMENT = 'GET_INCOME_STATEMENT';
export const GET_NUMBER_OF_SALES = 'GET_NUMBER_OF_SALES';
export const GET_REPORT_CHURN = 'GET_REPORT_CHURN';
export const GET_REPORT_COST = 'GET_REPORT_COST';

export const GET_LOCATION = 'GET_LOCATION';